# Generated by Django 3.2.21 on 2023-09-21 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20230920_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='max_value',
            new_name='goal_amount',
        ),
    ]
