# Generated by Django 3.2.21 on 2023-09-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_max_value_habit_goal_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='frequency',
            field=models.CharField(choices=[('D', 'Daily'), ('M', 'Monthly'), ('Y', 'Yearly')], default='D', max_length=1),
        ),
    ]
