# Generated by Django 3.2.21 on 2023-09-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_habit_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='units',
            field=models.CharField(blank=True, help_text='Custom units for the habit (e.g., hours, miles, tasks)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.CharField(choices=[('day', 'Per Day'), ('month', 'Per Month'), ('year', 'Per Year')], default='day', max_length=10),
        ),
    ]
