# Generated by Django 3.2.21 on 2023-09-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20230924_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='units',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
