# Generated by Django 3.2.21 on 2023-09-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_habit_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
