# Generated by Django 3.2.21 on 2023-09-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_habit_date_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_reset',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
