# Generated by Django 3.2.21 on 2023-09-29 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20230929_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='reminders',
        ),
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
