# Generated by Django 3.2.21 on 2023-09-29 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20230929_1405'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['category', 'completed', 'name']},
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
