# Generated by Django 3.2.21 on 2023-09-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20230929_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='units',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
