# Generated by Django 3.2.21 on 2023-11-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_habit_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='goal_amount',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='habit',
            name='name',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='habit',
            name='units',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
