# Generated by Django 3.2.21 on 2023-11-14 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20231110_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='goal_amount',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(99999999)]),
        ),
    ]
