# Generated by Django 3.2.21 on 2023-09-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image_public_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
