# Generated by Django 3.2.21 on 2023-09-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_alter_userprofile_color_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='selected_color_theme',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
